### ISSUE TITLE
Create new dashboard link in publisher

### ISSUE THREAD

**Issue by forrestkim00** [Recidiviz/justice-counts#1025]
**What needs to be done? Why does it need to be done?**
Hola! We are creating a link to Agency Dashboard from publisher. Here is the [Figma](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?type=design&node-id=9886%3A1555&mode=design&t=Ia5fEe9ZeJ8k2eX1-1)

**Additional context**
A couple notes that I left in the Figma as well: 
- This will link to whichever agency the user is currently in for Publisher.
- This link only exists if there is a live dashboard.
- Not dealing with the Superagencies edge case for now.

**Comment by mxosman** [comment]
@jwhrec - I'm trying to figure out the edge case for superagencies this is referring to - since they have their own metrics, they will have a dashboard as well just for their superagency-level metrics, right (please forgive me if I should already know this)? If they do get a dashboard, then no extra logic is needed since turning on their dashboard will do the trick and show this menu item. If they don't get a dashboard, then I can do a quick check for superagencies and hide the menu item.

**Comment by jwhrec** [comment]
Hi Mahmoud! That sounds like the perfect logic for now. Eventually we may want to think about how superagencies can access a list of dashboards for all their child agencies, but that's OOS

**Comment by mxosman** [comment]
Sorry, just to clarify - the logic depends on whether or not superagencies are meant to have a dashboard - they do get dashboards, right? I assumed so because they have their own metrics, but wanted to double check! No extra logic will be needed if so (aside from checking if the agency has the dashboard set to live).

But, if superagencies don't get a dashboard, then I can add extra logic to hide this (check if it's a superagency and hide the Agency Dashboard link from the menu if so).

>Eventually we may want to think about how superagencies can access a list of dashboards for all their child agencies, but that's OOS
Ah, great call!

**Comment by jwhrec** [comment]
Yes super agencies should have dashboards! For all agencies that don't have live data, we can hide the link.

**Comment by mxosman** [comment]
> Yes super agencies should have dashboards! For all agencies that don't have live data, we can hide the link.

Amazing! Thank you so much for clarifying, Jessica!
