### ISSUE TITLE
Implement redesigned Data Entry page.

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts#118]
Prototype: https://www.figma.com/proto/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?node-id=5160%3A14778&scaling=scale-down-width&page-id=1333%3A5802&starting-point-node-id=5160%3A14778
Designs: https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?node-id=1333%3A5802

--- 
Given the redesigned Review Page for Data Entry and other changes in the Publisher platform, we have redesigned the Data Entry page. Changes are summarized below, and can be previewed via this Figma prototype. 

- Do not render the context fields in this view. 
    - Instead, we should include a line in the rightmost panel that says: “Additional context can be viewed and entered via the Metric Configuration page in Settings.”
- The Navigation Bar should be replaced with three buttons: Review, Save as Draft, and  are moved to the Navigation bar, replacing the default items. 
    - Review -> Takes the user to the Review Page.
    - Save as Draft -> Takes the user back to Reports Page. 
    - Need Help? -> Newly designed “Help” page pops in from the side (instead showing up as a modal)? 
- Disabled Metrics: 
    - Disabled metrics should no longer appear as the heading. Instead, there should be a section at the bottom of the page that summarizes the metrics that have been disabled. 
    - Disabled breakdowns and fields should still appear in the form UI with the same disabled icon. 
        - Callouts for disabled breakdowns and fields should appear when hovering over any part of the element, not just when hovering over the icon. The color of the icon should match that of the callout (#171C2B) in this hover state. 

---

[New Data Entry Page: Prototype - Watch Video](https://www.loom.com/share/a19d3bc8fd834439832c334557930c30)

**Comment by ivan-kishko** [comment]
@hobuobi @lilidworkin Hello! Have a couple questions - old design had "review and publish" button on the right panel. When screen size was like medium it moved to bottom left corner (and because of that info that summary has at the bottom was disappearing), then on small screen this button went just to bottom. Since now we have this button at top bar I guess it would be fair to remove it in both cases and also leave summary details at the bottom until screen size is small and whole summary disappears. 
Second question is about "Need help" panel that appears from right - it takes like half screen but when screen is going to be small I guess this panel should take whole screen width, but for that I think I need some kind of breakpoint value in pixels or something like that.
Please let me know what do you think about that

**Comment by hobuobi** [comment]
Hey Ivan! Thanks for the comments. A few responses here: 
1. Regarding the responsive design, I have included more mocks [here](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?node-id=5392%3A13402) that should help to answer your questions. But your comments are basically correct: 
    a. Help panel should be the same width as the right panel after the first breakpoint (two columns), and then the full width after the second breakpoint (single column). 
    b. The info at the bottom of the summary panel should still disappear after the first breakpoint (replaced by the metric details); it should completely disappear after the second breakpoint. 
    c. The buttons should always be at the top. 
3. The slightly bigger padding is a mistake! Please ignore.
