### ISSUE TITLE
[Starter Task #6] See if possible to replace deploy_to_playtesting.sh with a GH action so it can easily be triggered on any frontend PR

### ISSUE THREAD

**Issue by terryttsai** [Recidiviz/justice-counts#228]
[Note from Lili -- this task was written a long time ago by someone no longer at Recidiviz, but I have updated it a bit!]

At a previous company, I found it very convenient that every front-end PR automatically deploys a build of its branch on an assigned URL. This made it very fast for convenient for PR reviewers and playtesters to see live demos of the work on the branch and give quick feedback. All the playtesting builds connected to the same staging backend so the data stayed consistent across playtesting builds. 

In our case, I don't think we need to spend the resources to deploy and host an instance for every single PR we put up. But it would be useful if there was quick way to set one up. 

We have a [deploy_for_playtesting.sh](https://github.com/Recidiviz/recidiviz-data/blob/main/recidiviz/tools/deploy/justice_counts/deploy_for_playtesting.sh) script that lets you specify a BE branch, FE branch, and playtesting traffic tag (see the [Cloud Run docs](https://cloud.google.com/run/docs/rollouts-rollbacks-traffic-migration#tags) for more info about how these tags work). This _mostly_ solves the problem, but the annoying things are:
* This has to be run from the command line, so only engineers can do it (e.g. if a PM wants to test our a PR, they have to bug an engineer to do a playtesting deploy)
* The script takes a long time to run
* If you make changes to your branch, you have to rerun the script

We should explore whether this script could be ported to GH Actions so it could easily be triggered by anyone on any version of any frontend PR. (No need to worry about doing this for backend PRs right now).

Note that, after your work on the [previous task](https://app.zenhub.com/workspaces/justice-counts--622109ea3bb6e0001d2d06ad/issues/gh/recidiviz/recidiviz-data/26213), deploy_for_playtesting.sh really doesn't do much besides just run our Cloud Build Trigger with the right parameters. Thus, it seems plausible that we could create a manually triggered GH Action that runs on any specified FE branch, [takes in any necessary parameters like URL tag](https://damienaicheh.github.io/github/actions/2022/01/20/set-dynamic-parameters-github-workflows-en.html) and then just runs the Cloud Build Trigger itself, essentially replacing deploy_for_playtesting.sh. 

In case it's helpful, Cloud Build Triggers can be triggered by [webhooks](https://cloud.google.com/build/docs/automate-builds-webhook-events?_ga=2.162844348.-1084490863.1700052988), so it seems like at the very least we could have our GH Action trigger it that way? There might be an easier way to accomplish the integration though.

[12/26/23 Update]: I spoke to Dan about this and he mentioned that Dana is currently working on getting a GH Action to have permission to "talk" to GCP. He mentioned that "workload identity federation" might be the way to go, and pointed me to these relevant tickets:
* https://github.com/Recidiviz/zenhub-tasks/issues/1547
* https://github.com/Recidiviz/zenhub-tasks/issues/1550
* https://github.com/Recidiviz/zenhub-tasks/issues/1553

**Comment by lilidworkin** [comment]
Thank you for writing this up @terryttsai ! I love this idea. A few thoughts:

* Agreed that extending our existing Cloud Build Trigger is the right way to do this. We currently have two triggers: one for [Publisher](https://console.cloud.google.com/cloud-build/triggers;region=global/edit/84614bd8-b45a-4788-af4f-950f6f6f526e?project=recidiviz-staging) and one for [Agency Dashboard](https://console.cloud.google.com/cloud-build/triggers;region=global/edit/6e08601d-8183-4d73-95f1-6011e05fcd52?project=recidiviz-staging).
* Both triggers work pretty similarly -- they both take as input a URL that points to the version of the frontend to "pull in" to the build, as well as a subdirectory to place the build. Then they build the Docker image!
* However, what these triggers _don't_ do is _deploy_ the new image to Cloud Run. But we could create new triggers that did this! (We'd want to create new triggers because the existing ones are currently used in the deploy scripts I wrote, so we don't want to modify those.)
* The only difference in the new triggers would be adding one step to the YAML configuration to actually deploy the new Docker image to Cloud Run. See this [documentation](https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run#continuous_deployment). 
* We'd have to make sure that this new step did two things: passed a `--tag` flag with a value of "playtesting" (or "terry-test" or whatever URL prefix we want) and also passed a `--no-traffic` flag, indicating that no default traffic should be redirected to this new deploy.
* Then, we'd have to figure out a way to call this Build Trigger via a "button" or something that could be triggered via a PR. This I'm not really sure about! It would need more investigation (possibly a post in #eng). I know you can trigger them via Python (see [here](https://github.com/Recidiviz/recidiviz-data/blob/main/recidiviz/tools/deploy/justice_counts/run_cloud_build_trigger.py)).

Let me know if this makes sense! If you want to tackle this (could be a fun project to do while the office is quiet over the holidays), I'd be happy to work on it together with you!

**Comment by terryttsai** [comment]
Awesome! Thanks for fleshing this out with information on how to do this. I think I'd want the url prefix to be the branch name to ensure a unique name for the purposes of the PR, and to also have a bot comment on the PR a link to the URL. I'd be down to work on this! 

Perhaps for now I should manually deploy my PRs and make sure we'd find the playtesting links useful before working on automating it?

**Comment by lilidworkin** [comment]
I think I'd want the url prefix to be the branch name to ensure a unique name for the purposes of the PR, and to also have a bot comment on the PR a link to the URL.

> Agreed, this makes a lot of sense!

> Perhaps for now I should manually deploy my PRs and make sure we'd find the playtesting links useful before working on automating it?

Also agreed, that makes a lot of sense and would be a good sanity check. You should be able to use the script to make it easy! https://github.com/Recidiviz/recidiviz-data/blob/main/recidiviz/tools/deploy/justice_counts/deploy_for_playtesting.sh

**Comment by morden35** [comment]
@lilidworkin is this safe to close?

**Comment by brandon-hills** [comment]
Submitted PR#26922 https://github.com/Recidiviz/recidiviz-data/pull/26922 to Add a GH action to trigger backend playtesting deployment!

workflow_dispatch can be triggered from the GH action "Deploy to JC Playtest", and intakes the following parameters:
<img width="747" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTdwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--34db4bea29844a962f44c9be15748aa42c34920a/Screenshot%202024-01-22%20at%204.10.50%E2%80%AFPM.png" alt="Screenshot 2024-01-22 at 4.10.50 PM.png" />

Tested this out by running it on a PR with a sentry alert and it triggered playtesting correctly!

 <img width="1656" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOS9wQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b8c9f3f027072108bee6e859ab8a32b59ee533c/Screenshot%202024-01-22%20at%204.11.53%E2%80%AFPM.png" alt="Screenshot 2024-01-22 at 4.11.53 PM.png" />

**Comment by brandon-hills** [comment]
Next steps: Create a similar GH action for triggering playtesting from Frontend PRs.

**Comment by brandon-hills** [comment]
Ran this by Jessica and she wondered if we could tag the person who triggered the GHA in the comment so that it notifies them by email.
Will look into this next

**Comment by lilidworkin** [comment]
@brandon-hills oh thanks for the heads up, that sounds good to me! I think I would first work on triggering from FE PRs and then circle back to this. We could also just have the person enter their email in the trigger form, rather than trying to identify it automatically, if that's easier :)

**Comment by brandon-hills** [comment]
Ran these cloud commands so that the `justice-counts` repo can authenticate via the `github-actions` Workload Identity Provider:

```
export PROJECT_ID="justice-counts-staging"
export REPO="Recidiviz/justice-counts"
export WORKLOAD_IDENTITY_POOL_ID=$(gcloud iam workload-identity-pools describe "github" \
  --project="justice-counts-staging" \
  --location="global" \
  --format="value(name)")

gcloud iam service-accounts add-iam-policy-binding "${PROJECT_ID}@${PROJECT_ID}.iam.gserviceaccount.com" \
  --project="${PROJECT_ID}" \
  --role="roles/iam.workloadIdentityUser" \
  --member="principalSet://iam.googleapis.com/${WORKLOAD_IDENTITY_POOL_ID}/attribute.repository/${REPO}"

gcloud iam service-accounts add-iam-policy-binding "${PROJECT_ID}@${PROJECT_ID}.iam.gserviceaccount.com" \
  --project="${PROJECT_ID}" \
  --role="roles/iam.workloadIdentityUser" \
  --member="principalSet://iam.googleapis.com/${WORKLOAD_IDENTITY_POOL_ID}/attribute.sub/${REPO}"
```

**Comment by brandon-hills** [comment]
Just committed the last two PRs related to this task.

https://github.com/Recidiviz/justice-counts/pull/1164
https://github.com/Recidiviz/recidiviz-data/pull/27133

Both frontend and backend github actions are completed!

**Comment by brandon-hills** [comment]
Also, we are now tagging the person who triggered the GHA so they're notified by email

**Comment by lilidworkin** [comment]
Amazing, awesome work on this @brandon-hills !
