### ISSUE TITLE
"Annual" --> "Annually"

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#296]
Matt from CSG requested the following tiny copy change of "Annual" to "Annually":
![Screenshot 2023-01-11 at 8.09.22 PM.png](https://images.zenhubusercontent.com/620e7d8c0c5fad82d897844d/6b0948db-e5b8-41ae-97ed-a5f615d6fdaf)

**Comment by lilidworkin** [comment]
cc @hobuobi who wanted to see the process for making a copy change like this! @mxosman can you cc him in the PR you put up?

**Comment by mxosman** [comment]
Sounds great! Will do! Quick question - we just want the UI label to change, right? We use the value "ANNUAL" throughout the FE and BE when doing comparisons (e.g. frequency === "ANNUAL"). I think we can just change the label and keep everything the same?

**Comment by hobuobi** [comment]
Oh yeah, nothing should need to change on the BE! 
I also don't think we should change the rectangular "Annual" labels that appear in other parts of the app; the only reason why I agreed to change it here was because it makes grammatical sense as a response to the question ("Yes, I can share this metric **annually**") vs describing a metric ("**monthly** admissions," "**annual** budget").

**Comment by mxosman** [comment]
Awesome! Thank you, Humphrey! That makes perfect sense! 🙏
