### ISSUE TITLE
[Bug] Team Management: All dropdowns show when a single “•••” option is clicked

### ISSUE THREAD

**Issue by mxosman** [Recidiviz/justice-counts#688]
Within Team Management, when you click on a user's “•••” option link, all dropdowns are rendered.

https://github.com/Recidiviz/justice-counts/assets/59492998/f8f8137f-848a-4dc1-bcea-a982399ed2fe

**Comment by ivan-kishko** [comment]
Hello @mxosman. I believe it is like this because email is the same for all those users (which is probably just empty string from what I see) I am not sure if email is required in order to be a user of justice counts BUT if you want I can instead use auth0_user_id OR we can just leave the id role to email and make it required

**Comment by mxosman** [comment]
Ohhh! Gotcha! That's a great point! E-mail is required so we should always have someone's e-mail and it will always be unique. It looks like these are just dummy users without an e-mail. I think this is safe to close and ignore. Thank you, Ivan!
