### ISSUE TITLE
Nit #8: Fix checkmarks in Data Entry page

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#697]
Item 8 in this [Figma file](https://www.figma.com/file/0UZOuDCrwGqWLKOhAyvGbc/Forrest's-First-Figma-File-(FFFF)?type=design&node-id=1173%3A45776&t=vmxUwNJ53SY7d0fk-1)

**Comment by ivan-kishko** [comment]
@lilidworkin Hello! I checked the exact same record from same agency which is on a screenshot and I have checkmarks. 

![Image](https://github.com/Recidiviz/justice-counts/assets/84838278/6117722a-3347-4adb-be0a-903a328875e6)

What should I do? Maybe You and Mahmoud can check this on your side?

**Comment by mxosman** [comment]
OK - so I took a quick look and you can run into that if you refresh while on the report. Something is out of sync with running validation on previous values when a user refreshes (likely something I goofed up). @ivan-kishko when you go to that page and refresh, do all the checkmarks disappear?

**Comment by ivan-kishko** [comment]
Well I still have checkmarks)

**Comment by lilidworkin** [comment]
Super interesting -- when I go to the staging app (https://publisher-staging.justice-counts.org/agency/151/records/4061) I don't have checkmarks, but when I run it locally, I do.

What is the logic that determines whether or not the checkmark appears? Could there be something non-deterministic or weird going on there, maybe a race condition?

**Comment by mxosman** [comment]
That's so bazaar! I'll dig into this more but the logic I believe lives in `TabbedDisaggregations` -- there's a `useEffect` that runs on every load that runs `updateDisaggregationHasInput`. Will need to figure out why it doesn't update at times... But, weird that we're not experiencing the same behavior.

I have checkmarks as well running locally regardless of refresh. But in staging, if I:
1. Click on a report from the report overview page, I see checkmarks in disaggregation tabs that have values
2. Refresh or go to the URL directly without clicking into the report from the overview page, the checkmarks disappear

Will look into this later/next week!

**Comment by mxosman** [comment]
OK - this one was a doozy...

If you want to replicate this behavior locally, you have to comment out `React.StrictMode` to avoid the extra mount/unmount behavior.
<img width="260" alt="Screenshot 2023-07-07 at 5 26 07 PM" src="https://github.com/Recidiviz/justice-counts/assets/59492998/b724f2d9-6964-4f18-b770-75199061af56">

The issue is in the `TabbedDisaggregations` component inside the `updateDisaggregationHasInput` function - in L97 `currentDisaggregationDimensions` is getting its value from the `formStore.disaggregations...` which has been coming up empty on load until the next re-render for some reason. Something is clearly out of sync - I'm happy to take this issue over so you can focus on dashboards, Ivan! It's old code that can use a bit of love and streamlining.

**Comment by mxosman** [comment]
OK - looks like we just need to make this an observable component and update the useEffect dependency array to run `updateDisaggregationHasInput` when disaggregations are loaded. I'll put up a fix next week.

<img width="645" alt="Screenshot 2023-07-07 at 6 51 40 PM" src="https://github.com/Recidiviz/justice-counts/assets/59492998/37cdbf2b-ce95-4cbb-8e83-f2d625407d34">

**Comment by lilidworkin** [comment]
WOW incredible investigating, @mxosman !! Thank you!!
