### ISSUE TITLE
Downloading data from "Explore Data" table view is broken

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/justice-counts#923]
I think it used to be the case that if you went to Explore Data, then clicked Switch to Data Table, and then clicked Download, it would download the data CSVs. Currently that link doesn't seem to do anything, though! Should be an easy fix since I know we already have the logic for getting the CSVs.

**Comment by mxosman** [comment]
Ah - great catch! I was looking through the codebase history and it doesn't look like this was implemented for the Publisher charts (which surprised me!) - but there is an implementation in agency dashboards. Super weird because I could've sworn I've seen this in Publisher as well... 

Will adjust - thank you for catching this!
